# Generated by Django 4.0.3 on 2022-03-31 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_news', models.ImageField(upload_to='')),
                ('dt', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 30, 20, 36, 49, 911782))),
                ('body', models.CharField(max_length=3000)),
            ],
        ),
    ]
